### PR TITLE
V1

### PR DESCRIPTION
**Pull request by prabinzz**
## Features;
 - Popup ui (simple)
 - On/Off switch 
 - Icon change to gray If extension is off. 
 - Works on currency format like $xxx, usd xxx , USD: xxx and some other. 
 - background sync.

### CODE REVIEW

**Comment by prabinzz** [comment]
@amitness  Is it working properly??

**Comment by amitness** [comment]
@prabinzz Yup, tested it on Amazon. Looks so cool :D

**Comment by amitness** [comment]
@prabinzz Share it with the community and get feedback. You've worked hard on this.

**Comment by prabinzz** [comment]
@amitness It doesn't affect style, That's what i like about it.    👍

**Pull request merged**
