### PR TITLE
Port to firefox 57+ using WebExtension API

### PR DESCRIPTION
**Pull request by dineshdb**
Straightforward port to firefox. Not much changes.

https://medium.com/@dineshdb/porting-nc-to-firefox-using-webextension-api-4045382fbf24

### CODE REVIEW

**Comment by dineshdb** [comment]
This PR will resolve #18.

**Comment by amitness** [comment]
@dineshdb Thanks for the help. I tested your fork on Chrome. Everything is working great but this breaks the options page on Chrome.

**Comment by amitness** [comment]
@dineshdb This should fix it. Add options_page: "options.html" so that options page works on chrome as well.

```
   "options_page": "options.html",
   "options_ui":{
      "options_page": "options.html",
      "browser_style": true
   },
```

**Comment by amitness** [comment]
Regarding the medium article, thanks for the great writeup. 

I also looked at your feedback. You're right that Bootstrap may be overkill for the simple options page. It was best at that time since this started as a prototype. I'll get it redesigned in vanilla CSS when I get time.

> jQuery is obsolete. Web APIs have grown so much that I consider jQuery a bloat.

You meant writing it in vanilla JS here?

**Comment by dineshdb** [comment]
Yeah I meant JS, sorry for the ambiguity. Regarding options page, it worked fine when I tested in Chromium (maybe due to cache). No problem in keeping both options for compatibility.

**Comment by dineshdb** [comment]
@amitness  Modified manifest.json as requested.

**Comment by amitness** [comment]
Thanks @dineshdb .

**Pull request merged**
